[2025-04-08T09:27:33.329+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T09:27:33.419+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-04-08T09:27:33.447+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-04-08T09:27:33.448+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-08T09:27:33.549+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_circuits> on 2025-03-30 00:00:00+00:00
[2025-04-08T09:27:33.563+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'formula1-etl-pipeline', 'transform.transform_dim_circuits', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpgdwh7xjv']
[2025-04-08T09:27:33.570+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask transform.transform_dim_circuits
[2025-04-08T09:27:33.574+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=607) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T09:27:33.577+0000] {standard_task_runner.py:63} INFO - Started process 661 to run task
[2025-04-08T09:27:33.727+0000] {task_command.py:426} INFO - Running <TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [running]> on host 1c2d39091a25
[2025-04-08T09:27:33.932+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='formula1-etl-pipeline' AIRFLOW_CTX_TASK_ID='transform.transform_dim_circuits' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-04-08T09:27:33.934+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T09:27:33.957+0000] {logging_mixin.py:188} INFO - /opt/***/dataset
[2025-04-08T09:27:34.034+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-08T09:27:34.059+0000] {logging_mixin.py:188} INFO - Đã tạo bảng thành công.
[2025-04-08T09:27:34.077+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-08T09:27:34.100+0000] {logging_mixin.py:188} INFO - Lỗi khi insert dữ liệu: duplicate key value violates unique constraint "dim_circuits_pkey"
DETAIL:  Key (circuitid)=(1) already exists.
[2025-04-08T09:27:34.106+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T09:27:34.110+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/transform_dim_circuits.py", line 40, in transform_dim_circuits
    warehouse_operator.insert_table(insert_table_querry, dim_circuits_df)
  File "/opt/airflow/dags/postgresql_operator.py", line 35, in insert_table
    cursor.executemany(query, values)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dim_circuits_pkey"
DETAIL:  Key (circuitid)=(1) already exists.

[2025-04-08T09:27:34.137+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=formula1-etl-pipeline, task_id=transform.transform_dim_circuits, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250408T092733, end_date=20250408T092734
[2025-04-08T09:27:34.180+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task transform.transform_dim_circuits (duplicate key value violates unique constraint "dim_circuits_pkey"
DETAIL:  Key (circuitid)=(1) already exists.
; 661)
[2025-04-08T09:27:34.225+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-08T09:27:34.272+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T09:27:34.312+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-08T09:59:49.214+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T09:59:49.246+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-04-08T09:59:49.254+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-04-08T09:59:49.254+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-08T09:59:49.266+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_circuits> on 2025-03-30 00:00:00+00:00
[2025-04-08T09:59:49.278+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'formula1-etl-pipeline', 'transform.transform_dim_circuits', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpea9seyea']
[2025-04-08T09:59:49.280+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=463) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T09:59:49.281+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask transform.transform_dim_circuits
[2025-04-08T09:59:49.281+0000] {standard_task_runner.py:63} INFO - Started process 477 to run task
[2025-04-08T09:59:49.326+0000] {task_command.py:426} INFO - Running <TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [running]> on host a06a1ce74445
[2025-04-08T09:59:49.403+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='formula1-etl-pipeline' AIRFLOW_CTX_TASK_ID='transform.transform_dim_circuits' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-04-08T09:59:49.405+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T09:59:49.416+0000] {logging_mixin.py:188} INFO - /opt/***/dataset
[2025-04-08T09:59:49.438+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-08T09:59:49.450+0000] {logging_mixin.py:188} INFO - Đã tạo bảng thành công.
[2025-04-08T09:59:49.461+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-08T09:59:49.488+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào bảng.
[2025-04-08T09:59:49.489+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-08T09:59:49.490+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T09:59:49.500+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=formula1-etl-pipeline, task_id=transform.transform_dim_circuits, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250408T095949, end_date=20250408T095949
[2025-04-08T09:59:49.535+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-08T09:59:49.549+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-08T10:40:34.833+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T10:40:34.880+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-04-08T10:40:34.893+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-04-08T10:40:34.894+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-08T10:40:34.910+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_circuits> on 2025-03-30 00:00:00+00:00
[2025-04-08T10:40:34.918+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'formula1-etl-pipeline', 'transform.transform_dim_circuits', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmp2arjhcyo']
[2025-04-08T10:40:34.920+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask transform.transform_dim_circuits
[2025-04-08T10:40:34.921+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=277) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T10:40:34.921+0000] {standard_task_runner.py:63} INFO - Started process 282 to run task
[2025-04-08T10:40:34.972+0000] {task_command.py:426} INFO - Running <TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [running]> on host b1ea421720de
[2025-04-08T10:40:35.067+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='formula1-etl-pipeline' AIRFLOW_CTX_TASK_ID='transform.transform_dim_circuits' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-04-08T10:40:35.068+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T10:40:35.090+0000] {logging_mixin.py:188} INFO - Lỗi khi đọc CSV: [Errno 2] No such file or directory: '/opt/***/dataset/datasets/rohanrao/formula-1-world-championship-1950-2020/versions/24/circuits.csv'
[2025-04-08T10:40:35.091+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-08T10:40:35.091+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T10:40:35.100+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=formula1-etl-pipeline, task_id=transform.transform_dim_circuits, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250408T104034, end_date=20250408T104035
[2025-04-08T10:40:35.135+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-08T10:40:35.150+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T10:40:35.151+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-08T10:49:03.467+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T10:49:03.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-04-08T10:49:03.517+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-04-08T10:49:03.518+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-08T10:49:03.539+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_circuits> on 2025-03-30 00:00:00+00:00
[2025-04-08T10:49:03.559+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'formula1-etl-pipeline', 'transform.transform_dim_circuits', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpgoy2q2dh']
[2025-04-08T10:49:03.562+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask transform.transform_dim_circuits
[2025-04-08T10:49:03.565+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=313) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T10:49:03.567+0000] {standard_task_runner.py:63} INFO - Started process 324 to run task
[2025-04-08T10:49:03.640+0000] {task_command.py:426} INFO - Running <TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [running]> on host 4e9e6de312e9
[2025-04-08T10:49:03.769+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='formula1-etl-pipeline' AIRFLOW_CTX_TASK_ID='transform.transform_dim_circuits' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-04-08T10:49:03.771+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T10:49:03.828+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-08T10:49:03.847+0000] {logging_mixin.py:188} INFO - Đã tạo bảng thành công.
[2025-04-08T10:49:03.865+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-08T10:49:03.900+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào bảng.
[2025-04-08T10:49:03.901+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-08T10:49:03.901+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T10:49:03.913+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=formula1-etl-pipeline, task_id=transform.transform_dim_circuits, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250408T104903, end_date=20250408T104903
[2025-04-08T10:49:03.950+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-08T10:49:03.972+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T10:49:03.973+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-15T07:09:07.110+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-15T07:09:07.146+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-04-15T07:09:07.156+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-04-15T07:09:07.157+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-15T07:09:07.171+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_circuits> on 2025-03-30 00:00:00+00:00
[2025-04-15T07:09:07.187+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=478) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-15T07:09:07.190+0000] {standard_task_runner.py:63} INFO - Started process 490 to run task
[2025-04-15T07:09:07.189+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'formula1-etl-pipeline', 'transform.transform_dim_circuits', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpszcj7to0']
[2025-04-15T07:09:07.192+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask transform.transform_dim_circuits
[2025-04-15T07:09:07.242+0000] {task_command.py:426} INFO - Running <TaskInstance: formula1-etl-pipeline.transform.transform_dim_circuits scheduled__2025-03-30T00:00:00+00:00 [running]> on host e24a12ae0bf8
[2025-04-15T07:09:07.346+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='formula1-etl-pipeline' AIRFLOW_CTX_TASK_ID='transform.transform_dim_circuits' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-04-15T07:09:07.348+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-15T07:09:07.412+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-15T07:09:07.448+0000] {logging_mixin.py:188} INFO - Đã tạo bảng thành công.
[2025-04-15T07:09:07.462+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-15T07:09:07.499+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào bảng.
[2025-04-15T07:09:07.500+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-15T07:09:07.500+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-15T07:09:07.511+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=formula1-etl-pipeline, task_id=transform.transform_dim_circuits, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250415T070907, end_date=20250415T070907
[2025-04-15T07:09:07.565+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-15T07:09:07.586+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
