[2025-04-04T15:42:34.247+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-04T15:42:34.280+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-04T15:42:34.288+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-04T15:42:34.289+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-04T15:42:34.303+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-04-03 00:00:00+00:00
[2025-04-04T15:42:34.312+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmp2nh_2wzc']
[2025-04-04T15:42:34.315+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask extract.extract_and_load_to_staging
[2025-04-04T15:42:34.318+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=449) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-04T15:42:34.319+0000] {standard_task_runner.py:63} INFO - Started process 458 to run task
[2025-04-04T15:42:34.371+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [running]> on host 662eee222047
[2025-04-04T15:42:34.451+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-04T15:42:34.453+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-04T15:42:37.094+0000] {logging_mixin.py:188} WARNING -   0%|          | 0.00/6.28M [00:00<?, ?B/s]
[2025-04-04T15:42:38.049+0000] {logging_mixin.py:188} WARNING -  16%|#5        | 1.00M/6.28M [00:00<00:05, 1.10MB/s]
[2025-04-04T15:42:38.202+0000] {logging_mixin.py:188} WARNING -  32%|###1      | 2.00M/6.28M [00:01<00:02, 2.17MB/s]
[2025-04-04T15:42:38.368+0000] {logging_mixin.py:188} WARNING -  48%|####7     | 3.00M/6.28M [00:01<00:01, 3.10MB/s]
[2025-04-04T15:42:38.553+0000] {logging_mixin.py:188} WARNING -  64%|######3   | 4.00M/6.28M [00:01<00:00, 3.78MB/s]
[2025-04-04T15:42:38.702+0000] {logging_mixin.py:188} WARNING -  80%|#######9  | 5.00M/6.28M [00:01<00:00, 4.53MB/s]
[2025-04-04T15:42:38.851+0000] {logging_mixin.py:188} WARNING -  96%|#########5| 6.00M/6.28M [00:01<00:00, 5.16MB/s]
[2025-04-04T15:42:38.871+0000] {logging_mixin.py:188} WARNING - 100%|##########| 6.28M/6.28M [00:01<00:00, 3.71MB/s]
[2025-04-04T15:42:39.685+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-04T15:42:39.686+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_data.py", line 13, in extract_and_load_to_staging
    dataset_path = kagglehub.dataset_download("rohanrao/formula-1-world-championship-1950-2020")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/datasets.py", line 35, in dataset_download
    path, _ = registry.dataset_resolver(h, path, force_download=force_download)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/registry.py", line 28, in __call__
    return impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/resolver.py", line 29, in __call__
    path, version = self._resolve(handle, path, force_download=force_download)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/http_resolver.py", line 135, in _resolve
    os.remove(archive_path)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dataset/datasets/rohanrao/formula-1-world-championship-1950-2020/24.archive'
[2025-04-04T15:42:39.702+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=scheduled__2025-04-03T00:00:00+00:00, execution_date=20250403T000000, start_date=20250404T154234, end_date=20250404T154239
[2025-04-04T15:42:39.721+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task extract.extract_and_load_to_staging ([Errno 2] No such file or directory: '/opt/airflow/dataset/datasets/rohanrao/formula-1-world-championship-1950-2020/24.archive'; 458)
[2025-04-04T15:42:39.748+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-04T15:42:39.776+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-04T15:42:39.782+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-04T15:52:04.187+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-04T15:52:04.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-04T15:52:04.241+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-04T15:52:04.242+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-04T15:52:04.257+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-04-03 00:00:00+00:00
[2025-04-04T15:52:04.267+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmp396dj9ez']
[2025-04-04T15:52:04.271+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask extract.extract_and_load_to_staging
[2025-04-04T15:52:04.272+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=449) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-04T15:52:04.273+0000] {standard_task_runner.py:63} INFO - Started process 458 to run task
[2025-04-04T15:52:04.333+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [running]> on host bf2b06959860
[2025-04-04T15:52:04.427+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-04T15:52:04.429+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-04T15:52:06.968+0000] {logging_mixin.py:188} WARNING -   0%|          | 0.00/6.28M [00:00<?, ?B/s]
[2025-04-04T15:52:07.930+0000] {logging_mixin.py:188} WARNING -  16%|#5        | 1.00M/6.28M [00:00<00:05, 1.09MB/s]
[2025-04-04T15:52:08.064+0000] {logging_mixin.py:188} WARNING -  32%|###1      | 2.00M/6.28M [00:01<00:02, 2.21MB/s]
[2025-04-04T15:52:08.182+0000] {logging_mixin.py:188} WARNING -  48%|####7     | 3.00M/6.28M [00:01<00:01, 3.36MB/s]
[2025-04-04T15:52:08.366+0000] {logging_mixin.py:188} WARNING -  80%|#######9  | 5.00M/6.28M [00:01<00:00, 5.60MB/s]
[2025-04-04T15:52:08.480+0000] {logging_mixin.py:188} WARNING - 100%|##########| 6.28M/6.28M [00:01<00:00, 6.82MB/s]
[2025-04-04T15:52:08.486+0000] {logging_mixin.py:188} WARNING - 100%|##########| 6.28M/6.28M [00:01<00:00, 4.35MB/s]
[2025-04-04T15:52:08.509+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-04T15:52:08.511+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_data.py", line 13, in extract_and_load_to_staging
    dataset_path = kagglehub.dataset_download("rohanrao/formula-1-world-championship-1950-2020")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/datasets.py", line 35, in dataset_download
    path, _ = registry.dataset_resolver(h, path, force_download=force_download)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/registry.py", line 28, in __call__
    return impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/resolver.py", line 29, in __call__
    path, version = self._resolve(handle, path, force_download=force_download)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/http_resolver.py", line 132, in _resolve
    _extract_archive(archive_path, out_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/http_resolver.py", line 264, in _extract_archive
    if tarfile.is_tarfile(archive_path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/tarfile.py", line 2795, in is_tarfile
    t = open(name)
        ^^^^^^^^^^
  File "/usr/local/lib/python3.12/tarfile.py", line 1802, in open
    return func(name, "r", fileobj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/tarfile.py", line 1870, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/gzip.py", line 192, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dataset/datasets/rohanrao/formula-1-world-championship-1950-2020/24.archive'
[2025-04-04T15:52:08.539+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=scheduled__2025-04-03T00:00:00+00:00, execution_date=20250403T000000, start_date=20250404T155204, end_date=20250404T155208
[2025-04-04T15:52:08.585+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task extract.extract_and_load_to_staging ([Errno 2] No such file or directory: '/opt/airflow/dataset/datasets/rohanrao/formula-1-world-championship-1950-2020/24.archive'; 458)
[2025-04-04T15:52:08.628+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-04T15:52:08.652+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-04T15:52:08.656+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-04T16:31:56.780+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-04T16:31:56.811+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-04T16:31:56.818+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-04T16:31:56.819+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-04T16:31:56.829+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-04-03 00:00:00+00:00
[2025-04-04T16:31:56.846+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=321) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-04T16:31:56.839+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmp87q1lt4q']
[2025-04-04T16:31:56.847+0000] {standard_task_runner.py:63} INFO - Started process 330 to run task
[2025-04-04T16:31:56.848+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask extract.extract_and_load_to_staging
[2025-04-04T16:31:56.905+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [running]> on host 3c57b6927613
[2025-04-04T16:31:56.985+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-04T16:31:56.986+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-04T16:31:57.769+0000] {logging_mixin.py:188} INFO - Tệp pit_stops.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T16:31:57.770+0000] {logging_mixin.py:188} INFO - Tệp qualifying.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T16:31:57.771+0000] {logging_mixin.py:188} INFO - Tệp races.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T16:31:57.772+0000] {logging_mixin.py:188} INFO - Tệp results.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T16:31:57.773+0000] {logging_mixin.py:188} INFO - Tệp seasons.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T16:31:57.774+0000] {logging_mixin.py:188} INFO - Tệp sprint_results.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T16:31:57.775+0000] {logging_mixin.py:188} INFO - Tệp status.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T16:31:57.775+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-04T16:31:57.776+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-04T16:31:57.787+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=scheduled__2025-04-03T00:00:00+00:00, execution_date=20250403T000000, start_date=20250404T163156, end_date=20250404T163157
[2025-04-04T16:31:57.825+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-04T16:31:57.843+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-04T16:31:57.845+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-04T18:20:53.112+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-04T18:20:53.146+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-04T18:20:53.154+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-04T18:20:53.154+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-04T18:20:53.168+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-04-03 00:00:00+00:00
[2025-04-04T18:20:53.180+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpj_juco6k']
[2025-04-04T18:20:53.183+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask extract.extract_and_load_to_staging
[2025-04-04T18:20:53.183+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=449) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-04T18:20:53.183+0000] {standard_task_runner.py:63} INFO - Started process 458 to run task
[2025-04-04T18:20:53.235+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [running]> on host 729d59a438a8
[2025-04-04T18:20:53.317+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-04T18:20:53.318+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-04T18:20:54.021+0000] {logging_mixin.py:188} INFO - Tệp pit_stops.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T18:20:54.022+0000] {logging_mixin.py:188} INFO - Tệp qualifying.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T18:20:54.023+0000] {logging_mixin.py:188} INFO - Tệp races.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T18:20:54.024+0000] {logging_mixin.py:188} INFO - Tệp results.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T18:20:54.025+0000] {logging_mixin.py:188} INFO - Tệp seasons.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T18:20:54.026+0000] {logging_mixin.py:188} INFO - Tệp sprint_results.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T18:20:54.027+0000] {logging_mixin.py:188} INFO - Tệp status.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-04T18:20:54.027+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-04T18:20:54.028+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-04T18:20:54.038+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=scheduled__2025-04-03T00:00:00+00:00, execution_date=20250403T000000, start_date=20250404T182053, end_date=20250404T182054
[2025-04-04T18:20:54.080+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-04T18:20:54.103+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-04T18:20:54.105+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T04:34:44.419+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:34:44.453+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:34:44.462+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:34:44.463+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:34:44.475+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-04-03 00:00:00+00:00
[2025-04-05T04:34:44.485+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpm9vmc0c6']
[2025-04-05T04:34:44.489+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask extract.extract_and_load_to_staging
[2025-04-05T04:34:44.490+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=321) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:34:44.491+0000] {standard_task_runner.py:63} INFO - Started process 332 to run task
[2025-04-05T04:34:44.541+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [running]> on host 0076f80062a6
[2025-04-05T04:34:44.623+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-05T04:34:44.624+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:34:45.348+0000] {logging_mixin.py:188} INFO - Tệp pit_stops.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:34:45.350+0000] {logging_mixin.py:188} INFO - Tệp qualifying.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:34:45.351+0000] {logging_mixin.py:188} INFO - Tệp races.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:34:45.352+0000] {logging_mixin.py:188} INFO - Tệp results.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:34:45.353+0000] {logging_mixin.py:188} INFO - Tệp seasons.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:34:45.354+0000] {logging_mixin.py:188} INFO - Tệp sprint_results.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:34:45.356+0000] {logging_mixin.py:188} INFO - Tệp status.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:34:45.356+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T04:34:45.357+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:34:45.364+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=scheduled__2025-04-03T00:00:00+00:00, execution_date=20250403T000000, start_date=20250405T043444, end_date=20250405T043445
[2025-04-05T04:34:45.427+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T04:34:45.448+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T04:34:45.450+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T04:49:53.410+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:49:53.448+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:49:53.457+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:49:53.458+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:49:53.472+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-04-03 00:00:00+00:00
[2025-04-05T04:49:53.481+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpnkuvz28d']
[2025-04-05T04:49:53.485+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask extract.extract_and_load_to_staging
[2025-04-05T04:49:53.486+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=386) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:49:53.487+0000] {standard_task_runner.py:63} INFO - Started process 396 to run task
[2025-04-05T04:49:53.538+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [running]> on host 7b82c2aa8826
[2025-04-05T04:49:53.620+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-05T04:49:53.622+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:49:54.325+0000] {logging_mixin.py:188} INFO - Tệp pit_stops.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:49:54.326+0000] {logging_mixin.py:188} INFO - Tệp qualifying.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:49:54.327+0000] {logging_mixin.py:188} INFO - Tệp races.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:49:54.328+0000] {logging_mixin.py:188} INFO - Tệp results.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:49:54.329+0000] {logging_mixin.py:188} INFO - Tệp seasons.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:49:54.330+0000] {logging_mixin.py:188} INFO - Tệp sprint_results.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:49:54.330+0000] {logging_mixin.py:188} INFO - Tệp status.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:49:54.331+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T04:49:54.331+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:49:54.341+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=scheduled__2025-04-03T00:00:00+00:00, execution_date=20250403T000000, start_date=20250405T044953, end_date=20250405T044954
[2025-04-05T04:49:54.383+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T04:49:54.413+0000] {taskinstance.py:3503} INFO - 6 downstream tasks scheduled from follow-on schedule check
[2025-04-05T04:49:54.414+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T04:53:57.475+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:53:57.515+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:53:57.523+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:53:57.524+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:53:57.540+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-04-03 00:00:00+00:00
[2025-04-05T04:53:57.549+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpp0fbxax3']
[2025-04-05T04:53:57.552+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask extract.extract_and_load_to_staging
[2025-04-05T04:53:57.554+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=323) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:53:57.555+0000] {standard_task_runner.py:63} INFO - Started process 333 to run task
[2025-04-05T04:53:57.605+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging scheduled__2025-04-03T00:00:00+00:00 [running]> on host 4766eee3ca7d
[2025-04-05T04:53:57.685+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-05T04:53:57.687+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:53:58.595+0000] {logging_mixin.py:188} INFO - Tệp pit_stops.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:53:58.598+0000] {logging_mixin.py:188} INFO - Tệp qualifying.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:53:58.600+0000] {logging_mixin.py:188} INFO - Tệp races.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:53:58.604+0000] {logging_mixin.py:188} INFO - Tệp results.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:53:58.606+0000] {logging_mixin.py:188} INFO - Tệp seasons.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:53:58.614+0000] {logging_mixin.py:188} INFO - Tệp sprint_results.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:53:58.625+0000] {logging_mixin.py:188} INFO - Tệp status.csv đã tồn tại tại /opt/***/dataset, không di chuyển.
[2025-04-05T04:53:58.626+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T04:53:58.627+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:53:58.642+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=scheduled__2025-04-03T00:00:00+00:00, execution_date=20250403T000000, start_date=20250405T045357, end_date=20250405T045358
[2025-04-05T04:53:58.854+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T04:53:58.895+0000] {taskinstance.py:3503} INFO - 6 downstream tasks scheduled from follow-on schedule check
[2025-04-05T04:53:58.908+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
